export default ['1 - Banco Do Brasil S.A (Bb)',
  '237 - Bradesco S.A',
  '335 - Banco Digio S.A',
  '260 - Nu Pagamentos S.A (Nubank)',
  '290 - Pagseguro Internet S.A',
  '323 - Mercado Pago – Conta Do Mercado Livre',
  '237 - Next Bank (Mesmo Código Do Bradesco)',
  '637 - Banco Sofisa S.A (Sofisa Direto)',
  '77 - Banco Inter S.A',
  '341 - Itaú Unibanco S.A',
  '104 - Caixa Econômica Federal (Cef)',
  '33 - Banco Santander Brasil S.A',
  '212 - Banco Original S.A',
  '756 - Bancoob (Banco Cooperativo Do Brasil)',
  '655 - Banco Votorantim S.A',
  '655 - Neon Pagamentos S.A (Memso Código Do Banco Votorantim)',
  '41 - Banrisul – Banco Do Estado Do Rio Grande Do Sul S.A',
  '389 - Banco Mercantil Do Brasil S.A',
  '422 - Banco Safra S.A',
  '70 - Banco De Brasília (Brb)',
  '136 - Unicred Cooperativa',
  '741 - Banco Ribeirão Preto',
  '739 - Banco Cetelem S.A',
  '743 - Banco Semear S.A',
  '100 - Planner Corretora De Valores S.A',
  '96 - Banco B3 S.A',
  '747 - Banco Rabobank Internacional Do Brasil S.A',
  '748 - Sicredi S.A',
  '752 - Bnp Paribas Brasil S.A',
  '91 - Unicred Central Rs',
  '399 - Kirton Bank',
  '108 - Portocred S.A',
  '757 - Banco Keb Hana Do Brasil S.A',
  '102 - Xp Investimentos S.A',
  '348 - Banco Xp S/A',
  '340 - Super Pagamentos S/A (Superdital)',
  '84 - Uniprime Norte Do Paraná',
  '180 - Cm Capital Markets Cctvm Ltda',
  '66 - Banco Morgan Stanley S.A',
  '15 - Ubs Brasil Cctvm S.A',
  '143 - Treviso Cc S.A',
  '62 - Hipercard Bm S.A',
  '74 - Bco. J.Safra S.A',
  '99 - Uniprime Central Ccc Ltda',
  '25 - Banco Alfa S.A.',
  '75 - Bco Abn Amro S.A',
  '40 - Banco Cargill S.A',
  '190 - Servicoop - 3973814',
  '63 - Banco Bradescard',
  '191 - Nova Futura Ctvm Ltda',
  '64 - Goldman Sachs Do Brasil Bm S.A',
  '97 - Ccc Noroeste Brasileiro Ltda',
  '16 - Ccm Desp Trâns Sc E Rs',
  '12 - Banco Inbursa',
  '3 - Banco Da Amazonia S.A',
  '60 - Confidence Cc S.A',
  '37 - Banco Do Estado Do Pará S.A',
  '159 - Casa Credito S.A',
  '172 - Albatross Ccv S.A',
  '85 - Coop Central Ailos',
  '114 - Central Cooperativa De Crédito No Estado Do Espírito Santo',
  '36 - Banco Bbi S.A',
  '394 - Banco Bradesco Financiamentos S.A',
  '4 - Banco Do Nordeste Do Brasil S.A.',
  '320 - Banco Ccb Brasil S.A',
  '189 - Hs Financeira',
  '105 - Lecca Cfi S.A',
  '76 - Banco Kdb Brasil S.A.',
  '82 - Banco Topázio S.A',
  '286 - Ccr De Ouro',
  '93 - Pólocred Scmepp Ltda',
  '273 - Ccr De São Miguel Do Oeste',
  '157 - Icap Do Brasil Ctvm Ltda',
  '183 - Socred S.A',
  '14 - Natixis Brasil S.A',
  '130 - Caruana Scfi',
  '127 - Codepe Cvc S.A',
  '79 - Banco Original Do Agronegócio S.A',
  '81 - Bbn Banco Brasileiro De Negocios S.A',
  '118 - Standard Chartered Bi S.A',
  '133 - Cresol Confederação',
  '121 - Banco Agibank S.A',
  '83 - Banco Da China Brasil S.A',
  '138 - Get Money Cc Ltda',
  '24 - Bco Bandepe S.A',
  '95 - Banco Confidence De Câmbio S.A',
  '94 - Banco Finaxis',
  '276 - Senff S.A',
  '137 - Multimoney Cc Ltda',
  '92 - Brk S.A',
  '47 - Banco Bco Do Estado De Sergipe S.A',
  '144 - Bexs Banco De Cambio S.A',
  '126 - Br Partners Bi',
  '301 - Bpp Instituição De Pagamentos S.A',
  '173 - Brl Trust Dtvm Sa',
  '119 - Banco Western Union ',
  '254 - Parana Banco S.A ',
  '268 - Barigui Ch ',
  '107 - Banco Bocom Bbm S.A ',
  '412 - Banco Capital S.A ',
  '124 - Banco Woori Bank Do Brasil S.A',
  '149 - Facta S.A. Cfi ',
  '197 - Stone Pagamentos S.A ',
  '142 - Broker Brasil Cc Ltda ',
  '389 - Banco Mercantil Do Brasil S.A. ',
  '184 - Banco Itaú Bba S.A ',
  '634 - Banco Triangulo S.A (Banco Triângulo) ',
  '545 - Senso Ccvm S.A ',
  '132 - Icbc Do Brasil Bm S.A ',
  '298 - Vips Cc Ltda ',
  '129 - Ubs Brasil Bi S.A ',
  '128 - Ms Bank S.A Banco De Câmbio ',
  '194 - Parmetal Dtvm Ltda ',
  '310 - Vortx Dtvm Ltda ',
  '163 - Commerzbank Brasil S.A Banco Múltiplo ',
  '280 - Avista S.A ',
  '146 - Guitta Cc Ltda ',
  '279 - Ccr De Primavera Do Leste ',
  '182 - Dacasa Financeira S/A ',
  '278 - Genial Investimentos Cvm S.A ',
  '271 - Ib Cctvm Ltda ',
  '21 - Banco Banestes S.A ',
  '246 - Banco Abc Brasil S.A ',
  '751 - Scotiabank Brasil ',
  '208 - Banco Btg Pactual S.A ',
  '746 - Banco Modal S.A ',
  '241 - Banco Classico S.A ',
  '612 - Banco Guanabara S.A',
  '604 - Banco Industrial Do Brasil S.A ',
  '505 - Banco Credit Suisse (Brl) S.A ',
  '196 - Banco Fair Cc S.A ',
  '300 - Banco La Nacion Argentina',
  '477 - Citibank N.A ',
  '266 - Banco Cedula S.A ',
  '122 - Banco Bradesco Berj S.A ',
  '376 - Banco J.P. Morgan S.A ',
  '473 - Banco Caixa Geral Brasil S.A ',
  '745 - Banco Citibank S.A ',
  '120 - Banco Rodobens S.A ',
  '265 - Banco Fator S.A ',
  '7 - Bndes (Banco Nacional Do Desenvolvimento Social)',
  '188 - Ativa S.A Investimentos',
  '134 - Bgc Liquidez Dtvm Ltda',
  '641 - Banco Alvorada S.A',
  '29 - Banco Itaú Consignado S.A',
  '243 - Banco Máxima S.A',
  '78 - Haitong Bi Do Brasil S.A',
  '111 - Banco Oliveira Trust Dtvm S.A',
  '17 - Bny Mellon Banco S.A',
  '174 - Pernambucanas Financ S.A',
  '495 - La Provincia Buenos Aires Banco',
  '125 - Brasil Plural S.A Banco',
  '488 - Jpmorgan Chase Bank',
  '65 - Banco Andbank S.A ',
  '492 - Ing Bank N.V ',
  '250 - Banco Bcv ',
  '145 - Levycam Ccv Ltda ',
  '494 - Banco Rep Oriental Uruguay ',
  '253 - Bexs Cc S.A ',
  '269 - Hsbc Banco De Investimento ',
  '213 - Bco Arbi S.A ',
  '139 - Intesa Sanpaolo Brasil S.A ',
  '18 - Banco Tricury S.A ',
  '630 - Banco Intercap S.A ',
  '224 - Banco Fibra S.A ',
  '600 - Banco Luso Brasileiro S.A ',
  '623 - Banco Pan ',
  '204 - Banco Bradesco Cartoes S.A ',
  '479 - Banco Itaubank S.A ',
  '456 - Banco Mufg Brasil S.A',
  '464 - Banco Sumitomo Mitsui Brasil S.A ',
  '613 - Omni Banco S.A ',
  '652 - Itaú Unibanco Holding Bm S.A ',
  '653 - Banco Indusval S.A ',
  '69 - Banco Crefisa S.A ',
  '370 - Banco Mizuho S.A ',
  '249 - Banco Investcred Unibanco S.A',
  '318 - Banco Bmg S.A',
  '626 - Banco Ficsa S.A',
  '270 - Sagitur Cc Ltda',
  '366 - Banco Societe Generale Brasil',
  '113 - Magliano S.A ',
  '131 - Tullett Prebon Brasil Cvc Ltda ',
  '11 - C.Suisse Hedging - Griffo Cv S.A (Credit Suisse)',
  '611 - Banco Paulista ',
  '755 - Bofa Merrill Lynch Bm S.A ',
  '89 - Ccr Reg Mogiana ',
  '643 - Banco Pine S.A ',
  '140 - Easynvest – Título Cv S.A ',
  '707 - Banco Daycoval S.A ',
  '288 - Carol Dtvm Ltda ',
  '101 - Renascenca Dtvm Ltda ',
  '487 - Deutsche Bank S.A Banco Alemão',
  '233 - Banco Cifra ',
  '177 - Guide ',
  '633 - Banco Rendimento S.A',
  '218 - Banco Bs2 S.A ',
  '292 - Bs2 Distribuidora De Títulos E Investimentos ',
  '169 - Banco Olé Bonsucesso Consignado S.A ',
  '293 - Lastro Rdv Dtvm Ltda ',
  '285 - Frente Cc Ltda ',
  '80 - B&T Cc Ltda ',
  '753 - Novo Banco Continental S.A Bm ',
  '222 - Banco Crédit Agricole Br S.A ',
  '754 - Banco Sistema ',
  '98 - Credialiança Ccr ',
  '610 - Banco Vr S.A ',
  '712 - Banco Ourinvest S.A ',
  '10 - Credicoamo ',
  '283 - Rb Capital Investimentos Dtvm Ltda ',
  '217 - Banco John Deere S.A ',
  '117 - Advanced Cc Ltda ',
  '336 - Banco C6 S.A (C6 Bank)',
  '654 - Banco A.J. Renner S.A']
